import type { Lesson } from '../lessons';

export const lessons: Lesson[] = [
  // Lessons will be generated by orchestrate script
  {
    day: 1,
    title: "The Architecture of Perpetual Wealth",
    date: "2026-04-24",
    image: "images/goldman-sachs-trust-funds/day-1.jpg",
    audio: "audio/goldman-sachs-trust-funds/day-1",
    sonnet: `**🪶 Sonnet I: The Architecture of Perpetual Wealth**

Upon foundations built with foresight's art,
The wealthy craft their dynasties to last,
While lesser fortunes crumble and depart,
Great houses anchor futures to the past.

With trust and partnership as mortar strong,
They raise their towers high beyond the storm,
Where money breeds in chambers built to spawn
New wealth in ever-multiplying form.

Through offshore winds and regulatory change,
These structures stand while empires rise and fall,
Their architects of fortune strange yet sage
Have learned that systems conquer time's cruel call.

*For those who build with centuries in mind,*
*Leave monuments that death itself can't find.*`,
    standard: `💎 **Day 1: The Architecture of Perpetual Wealth**

When Goldman Sachs manages $2.5 trillion for the world's ultra-wealthy, they're not just moving money—they're building dynasties that can outlast empires. Today we explore the foundational principles that separate temporary riches from generational fortunes.

🧱 **The Concept**
True wealth preservation requires architectural thinking: building multi-layered structures designed to survive market crashes, political upheavals, and generational transfers.

❓ **Why It Matters**
Family fortunes that survive centuries don't happen by accident—they're engineered through sophisticated trust structures, tax strategies, and governance frameworks. The difference between rich families and wealthy dynasties lies in their ability to think beyond individual lifespans and create systems that compound wealth across generations.

⚙️ **How It Works**
The ultra-wealthy use a combination of dynasty trusts, family limited partnerships, and private placement life insurance to create tax-efficient wealth transfer mechanisms. For example, a billionaire might establish a generation-skipping trust that holds family business interests, real estate, and alternative investments, allowing wealth to grow tax-free for 100+ years while providing liquidity to heirs through carefully structured distributions. Private banks like Goldman Sachs layer these structures with offshore entities, family offices, and sophisticated hedging strategies to protect against currency devaluation, regulatory changes, and market volatility.

🎯 **Private Wealth Wisdom**
Wealth architecture isn't about avoiding taxes—it's about creating systems where money works harder than people, and structures outlast their creators.

❓ **Tomorrow's Question** — If the greatest threat to generational wealth isn't market crashes or economic downturns, but rather the heirs themselves, how do the ultra-wealthy design structures that protect fortunes from their own family members' potential mismanagement?`,
    parable: `Sterling adjusted his Hermès tie as he entered the mahogany-paneled conference room on the forty-second floor, where Aurelius sat studying a leather-bound portfolio with the intensity of a master architect reviewing cathedral blueprints.

"Tell me, Sterling," Aurelius began without looking up, his silver hair catching the morning light streaming through floor-to-ceiling windows overlooking Manhattan, "what separates the Rothschilds from the robber barons of the Gilded Age?"

Sterling shifted uncomfortably. "Market timing? Better investments?"

Aurelius finally raised his eyes, a knowing smile creasing his weathered face. "The robber barons built fortunes. The Rothschilds built systems." He opened the portfolio, revealing intricate diagrams that resembled both family trees and engineering schematics. "When I began managing the Pemberton dynasty in 1983, their patriarch told me something that changed how I understood wealth: 'Money is mortal, but structures are immortal.'"

"Look at these trust architectures," Aurelius continued, his finger tracing connections between entities spanning multiple jurisdictions. "Dynasty trusts in South Dakota, family limited partnerships in Delaware, private placement life insurance in Bermuda—each component designed not just for today's tax code, but for tax codes that haven't been written yet. The Pembertons' great-great-grandchildren will inherit not just wealth, but the machinery that creates wealth."

Sterling leaned forward, mesmerized. "But surely the complexity—"

"Is precisely the point," Aurelius interrupted gently. "Complexity creates resilience. When you spread risk across generations, jurisdictions, and asset classes, you're not just preserving capital—you're ensuring that the family's financial DNA can adapt and evolve long after we're gone."

**Moral:** True wealth isn't measured in dollars but in decades—the families who think like institutions become institutions themselves.

**Tomorrow:** Sterling discovers why the greatest enemy of generational wealth often sleeps in the family mansion...`,
  },
  {
    day: 2,
    title: "The Incentive Architecture",
    date: "2026-04-25",
    image: "images/goldman-sachs-trust-funds/day-2.jpg",
    audio: "audio/goldman-sachs-trust-funds/day-2",
    sonnet: `**🪶 Sonnet II: The Incentive Architecture**

Not age alone should loose the golden chain
That binds great fortunes to their rightful heirs,
But merit earned through struggle, growth, and pain—
The proven worth that true succession bears.
Let diplomas won and service rendered long
Unlock the vaults where family treasures sleep,
While charity and purpose make one strong,
And idle hands find barren coffers keep.
The wise patriarch builds not walls of stone,
But bridges crossed by character alone,
Where each descendant proves their noble right
To bear the burden wealth and wisdom bring.
*For fortunes fade when given without test,
But flourish when the worthy are blessed.*`,
    standard: `💎 Day 2: The Incentive Architecture

The ultra-wealthy protect fortunes from heir mismanagement through sophisticated **incentive structures** that align financial rewards with responsible behavior. These systems use **graduated distribution schedules**, **performance milestones**, and **trustee oversight** to ensure heirs must demonstrate competence before accessing significant capital.

🧱 **The Concept**
Incentive-based trust structures condition wealth distribution on specific achievements, behaviors, or life milestones rather than simple age requirements.

❓ **Why It Matters**
Traditional age-based trusts often release substantial wealth to unprepared heirs at arbitrary milestones like 25 or 30. Goldman Sachs structures instead create **meritocratic wealth distribution** that rewards education completion, career development, charitable involvement, or demonstrated financial responsibility. This approach transforms potential spendthrift heirs into engaged stewards of family legacy.

⚙️ **How It Works**
A typical Goldman incentive trust might release 25% of principal upon college graduation, another 25% after five years of steady employment, and additional distributions tied to charitable giving or business creation. **Negative incentives** can reduce distributions for substance abuse, criminal behavior, or financial irresponsibility. Some structures include **trustee discretion clauses** allowing professional managers to withhold funds during periods of heir instability. The Rockefeller family famously uses **family employment requirements** where heirs must work outside the family business for several years before joining family enterprises. More sophisticated structures include **peer review panels** where family members evaluate each other's readiness for increased responsibility.

🎯 **Private Wealth Wisdom**
The most successful generational wealth transfers don't just preserve capital—they preserve the character traits that created the fortune in the first place.

❓ **Tomorrow's Question** — If traditional investment diversification spreads risk across asset classes, why do Goldman Sachs' most sophisticated clients deliberately concentrate massive portions of their wealth in illiquid, often opaque alternative investments that most advisors would consider dangerously risky?`,
    parable: `Sterling studied the thick trust document spread across Aurelius's mahogany desk, its pages dense with conditional clauses and performance metrics. "This reads more like a corporate compensation plan than a family inheritance," he observed.

Aurelius smiled knowingly. "Precisely. You see, my young colleague, the Ashford family learned this lesson the hard way. The grandfather built a shipping empire through relentless discipline and strategic thinking. The father, raised in comfort but taught these values, expanded the business globally. But by the third generation, wealth had become an assumption rather than an achievement."

He pointed to a specific clause. "Young Theodore Ashford was brilliant but directionless—until his trust required him to complete a master's degree and work for a competitor for three years before accessing his inheritance. The 'punishment' of earning his own way transformed him into the family's most capable leader."

"But what about rebellion?" Sterling asked. "Surely some heirs simply reject these constraints?"

"Some do," Aurelius nodded. "And that, paradoxically, serves the family's interests. Those who reject responsibility self-select out of wealth stewardship. The structure doesn't create character—it reveals it, and rewards it accordingly. We've designed a system where the family fortune naturally flows toward the most capable hands, regardless of birth order or parental favoritism."

Sterling traced the document's margins, understanding dawning. "So the trust becomes a crucible—testing and refining each generation."

"Indeed. And tomorrow, I'll show you why these same families deliberately embrace risks that would terrify most investors."

**Moral**: True wealth preservation requires preserving not just capital, but the qualities that created it.

**Tomorrow**: Discover why concentrated risk often proves safer than diversification for the ultra-wealthy.`,
  },
];
