import type { Lesson } from '../lessons';

export const lessons: Lesson[] = [
  // Lessons will be generated by orchestrate script
  {
    day: 1,
    title: "The Foundation of Secure Attachment",
    date: "2026-05-02",
    image: "images/raising-kids/day-1.jpg",
    audio: "",
    sonnet: `**🪶 Sonnet I: The Foundation of Secure Attachment**

When tender cries pierce through the midnight air,
And weary hearts debate 'tween rest and care,
The parent's choice reveals what love can bear—
To answer need with presence always there.

Like seedlings drinking deep from morning dew,
The child who finds their calls are always heard
Grows roots of trust that anchor strong and true,
Their foundation built on every word.

For in those moments when we choose to hold,
To soothe the fears that shake their tiny frame,
We teach a truth more precious than pure gold—
That they are worthy, loved, and free from shame.

*Though some may warn of spoiling tender hearts,*
*Secure attachment is where strength truly starts.*`,
    standard: `👶 **Day 1: The Foundation of Secure Attachment**
Welcome to our journey through the art and science of parenting. We begin with the most fundamental building block of healthy development.

🧱 **The Concept**
**Secure attachment** is the emotional bond formed when a caregiver consistently responds to their child's needs with sensitivity and reliability.

❓ **Why It Matters**
Secure attachment serves as the foundation for a child's emotional regulation, self-worth, and future relationships. Children with secure attachments develop greater resilience, empathy, and the ability to trust others throughout their lives.

⚙️ **How It Works**
Secure attachment develops through thousands of small interactions—responding promptly when your baby cries, maintaining eye contact during feeding, and providing comfort during distress. It's not about being a perfect parent, but about being **consistently attuned** to your child's emotional and physical needs. For example, when a toddler falls and looks to you for reassurance, your calm response and gentle comfort teaches them that you are a safe haven. This **attachment security** becomes their internal working model for how relationships function, influencing everything from their confidence to explore the world to their ability to form healthy partnerships as adults.

🎯 **Parenting Wisdom**
Attachment is built in moments, not milestones. Trust your instincts—your responsive presence is more powerful than any parenting technique.

❓ **Tomorrow's Question** — If secure attachment requires consistent responsiveness, how do we balance meeting our child's needs while also teaching them to tolerate frustration and develop independence?`,
    parable: `Asha stood in her kitchen at 3 AM, swaying gently with her crying infant son, her eyes heavy with exhaustion. The baby books scattered across her counter offered conflicting advice—some demanding strict schedules, others advocating complete child-led approaches. Her mother-in-law's voice echoed in her mind: "You're spoiling him. Let him cry it out."

Elder Mira appeared at the doorway, her silver hair catching the soft lamplight. She had raised seven children across four decades, weathering every parenting philosophy that had come and gone.

"I see you wrestling with more than just a sleepless night," Mira observed, settling into the rocking chair. "Tell me, what does your heart say when he cries?"

"It says to hold him," Asha whispered, "but everyone says I'm creating bad habits."

Mira smiled, her eyes crinkling with memory. "I once knew a gardener who worried that watering her seedlings too often would make them weak. So she let them struggle, thinking it would make them strong. But the plants that grew tallest and most resilient were those that first received abundant water—their roots grew deep and sure, trusting that nourishment would come."

She gestured toward the baby, now quieting in Asha's arms. "Attachment is like those deep roots. When a child learns that their needs matter, that calling out brings comfort, they develop an unshakeable trust in the world's goodness. This becomes their foundation for everything else—confidence to explore, ability to self-soothe, and eventually, the capacity to form their own healthy relationships."

"But how will he ever become independent?" Asha asked.

"A child who trusts in your availability becomes brave enough to venture away," Mira replied. "It's the anxiously attached children who cling most desperately, because they've learned that love is unreliable."

As dawn approached, Asha felt her shoulders relax. Her instincts weren't weakness—they were wisdom.

**Moral:** Secure attachment is not about perfection, but about presence. The roots of independence grow strongest in the soil of consistent love.

*Tomorrow, Elder Mira will reveal the delicate balance between nurturing and fostering resilience...*`,
  },
  {
    day: 2,
    title: "The Dance of Attunement and Boundaries",
    date: "2026-05-03",
    image: "images/raising-kids/day-2.jpg",
    audio: "audio/raising-kids/day-2",
    sonnet: `**🪶 Sonnet II: The Dance of Attunement and Boundaries**

Beneath the surface of each cry and smile
Lies deeper truth that loving eyes can read,
The parent's gift: to pause, observe a while,
And match response to child's authentic need.

Not every tear demands immediate ease,
Nor every laugh calls for our swift reply,
But sensing when to soothe and when to tease
The space between — this wisdom we apply.

Through countless moments, small yet profound,
We learn the language of our child's heart,
In daily dance where love and limits bound
The sacred choreography of our art.

*When parent truly sees what child would say,*
*Both souls are met and trust grows day by day.*`,
    standard: `👶 Day 2: The Dance of Attunement and Boundaries

The balance between responsiveness and fostering independence lies in **graduated responsiveness** — being consistently available while allowing age-appropriate delays and frustrations. We respond immediately to genuine distress while letting children work through minor challenges, teaching them that feelings are manageable and they are capable.

🧱 **The Concept**
Attunement is the parent's ability to read, understand, and respond appropriately to their child's emotional and physical cues, creating a secure base from which the child can explore the world.

❓ **Why It Matters**
Children who experience consistent attunement develop better emotional regulation, stronger self-esteem, and more secure relationships throughout their lives. When parents accurately read and respond to their child's needs, they're teaching the child to trust their own internal signals and the reliability of human connection.

⚙️ **How It Works**
Attunement happens through **micro-moments** of connection — making eye contact when your toddler shows you a toy, reflecting back their emotions ("You seem frustrated with that puzzle"), and matching their energy level when they're excited. It's not about being perfect, but about **repair** when we miss the mark. A parent might say, "I see you were trying to tell me something important, and I was distracted. Can you tell me again?" This teaches children that relationships can be mended and that their feelings matter. The key is **contingent responsiveness** — your response matches what your child actually needs in that moment, not what you think they should need.

🎯 **Parenting Wisdom**
Attunement is less about getting it right every time and more about staying curious about your child's inner world. When we truly see our children, they learn to see themselves.

❓ **Tomorrow's Question** — If children naturally co-regulate through their parent's nervous system, how do we manage our own emotional states when we're triggered by our child's behavior, especially when our instinct is to react rather than respond?`,
    parable: `Elder Mira found Asha in the garden, bouncing her fussing infant while tears streamed down her face. "She's been crying for an hour," Asha whispered. "I've fed her, changed her, held her — nothing works. Maybe I'm not cut out for this."

Mira settled beside them on the stone bench, her weathered hands gentle as she observed. "Tell me what you see in her face," she said softly.

Asha looked down at her daughter's red, scrunched features. "Anger? Frustration? I don't know — just... upset?"

"Look deeper," Mira encouraged. "What do her eyes tell you? Her little fists?"

As Asha gazed more intently, something shifted in her perception. "Her eyes... they're wide, almost searching. And her fists are clenched, but they're reaching toward me, not pushing away."

"Ah," Mira smiled. "Now you're beginning to see her, not just her distress. What might she be trying to tell you?"

Asha felt a flutter of understanding. She adjusted her hold, bringing the baby closer to her chest, and began humming a melody that had been playing in her mind all morning. Almost immediately, the crying softened to hiccups, then to quiet attention.

"She wasn't hungry or wet," Asha marveled. "She was... lonely? Wanting connection?"

"You learned to attune," Mira said, watching the baby's eyes grow heavy. "To read beneath the surface and respond to what she truly needed. This is how trust is built — not through perfect responses, but through the effort to truly see and understand."

**Moral:** *Attunement is the art of seeing beyond behavior to the heart's true need, creating connection through understanding rather than assumption.*

*Tomorrow, Asha will discover how her own emotional weather affects her child's inner climate...*`,
  },
];
