import type { Lesson } from '../lessons';

export const lessons: Lesson[] = [
  // Lessons will be generated by orchestrate script
  {
    day: 1,
    title: "The Game Behind the Game",
    date: "2026-04-25",
    image: "images/relationship-games/day-1.jpg",
    audio: "audio/relationship-games/day-1",
    sonnet: `**🪶 Sonnet I: The Game Behind the Game**

Beneath each smile and whispered sweet caress,
Lies hidden theater of power and control,
Where hearts perform their scripted tenderness
While minds pursue a more strategic goal.

The surface speaks of love and pure desire,
Yet underneath, the chess pieces advance,
Each gesture calculated to inspire
The perfect step in this romantic dance.

She mentions others while she holds your hand,
He arrives late to test your patience true,
These contradictions few can understand—
The game behind the game they play on you.

*For those who see both stages of the play*
*Hold power over hearts that look away.*`,
    standard: `🎭 Day 1: The Game Behind the Game

Welcome to the hidden psychology of romantic power dynamics. Love may feel spontaneous, but beneath every romance lies a complex web of psychological games, power plays, and unconscious strategies.

🧱 **The Concept**
Romantic interactions operate on multiple levels simultaneously — the surface conversation and the hidden psychological game underneath.

❓ **Why It Matters**
Most people focus only on what's being said while missing the real dynamics at play. Understanding these hidden games protects you from manipulation and helps you recognize when someone is being genuine versus strategic. The person who sees both levels holds the real power.

⚙️ **How It Works**
Every romantic interaction contains both **explicit communication** ("I had a great time tonight") and **implicit messaging** (arriving 20 minutes late to establish dominance). Consider the classic "hot and cold" behavior: someone texts constantly for days, then disappears for a week. The surface message is inconsistency, but the hidden game is creating **intermittent reinforcement** — the most addictive psychological pattern known. Other examples include the "accidental" mention of other romantic options, strategic vulnerability sharing to create bonding, or withholding affection to increase its perceived value. These aren't always conscious manipulations; they're often unconscious strategies learned through trial and error.

🎯 **Relationship Strategy Wisdom**
The most dangerous games are the ones you don't realize you're playing.

❓ **Tomorrow's Question** — If someone's actions consistently contradict their words, which should you believe — and what does your choice reveal about your own psychological vulnerabilities?`,
    parable: `Riven sat across from their latest romantic interest at the coffee shop, replaying the conversation in their mind. Everything had seemed perfect — the laughter, the connection, the promise to "definitely meet again soon." Yet something felt off, like watching a play where the actors occasionally broke character.

"You look troubled," came a familiar voice. The Mirror materialized in the empty chair beside them, their form shifting like smoke given substance. "Another beautiful performance?"

"I don't understand," Riven confessed. "They seemed so interested, but then they mentioned their ex three times and kept checking their phone. Were they into me or not?"

The Mirror smiled knowingly. "You're watching the wrong theater, dear child. You saw the play they performed for you — charming, attentive, promising. But did you notice the shadow play happening simultaneously?"

With a gesture, the Mirror conjured an ethereal projection of the recent date. "Watch again, but this time see both stages." The scene replayed, but now Riven could see the subtle power moves: the strategic mentions of other options, the calculated pauses before responding to create tension, the way their date positioned themselves to be seen by as many people as possible.

"Every romantic encounter is a double performance," the Mirror explained. "The conscious courtship dance everyone sees, and the unconscious psychological chess match happening beneath. Most people are so enchanted by the surface performance that they miss the real game entirely."

Riven's eyes widened as the pattern became clear. "So they weren't genuinely interested?"

"Perhaps they were, perhaps they weren't," the Mirror replied, dissolving into mist. "But until you learn to see both games simultaneously, you'll always be a player rather than a strategist."

**Moral:** The most dangerous romantic games are played on stages you cannot see.

*Tomorrow, The Mirror will reveal why contradictions between words and actions create the most powerful psychological traps...*`,
  },
];
